# Nordic-darker color palette
#normalgreen	user
#normalcyan	dir
#normalyellow	git
#normalmagenta	version
#normalblue	doc (from dracula color palette)
#normalyellow	time (from dracula color palette)

# some extra symbols
# 
# 

#           _     _ 
#  ______ _(_) __| |
# |_  / _` | |/ _` |
#  / / (_| | | (_| |
# /___\__,_|_|\__,_|	zaid-hassan
 
# ---------------------------------------------------------------
format = """
[░▒▓](normalgreen)\
$os\
$username\
[](bg:normalcyan fg:normalgreen)\
$directory\
[](fg:normalcyan bg:normalyellow)\
$git_branch\
$git_status\
[](fg:normalyellow bg:normalmagenta)\
$c\
$python\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:normalmagenta bg:normalblue)\
$docker_context\
[](fg:normalblue bg:normalyellow)\
$time\
[ ](fg:normalyellow)\
\n
$cmd_duration\
$character\
"""
#add_newline = false

palette = 'gruvbox'

[palettes.gruvbox]
background = '#282828'
foreground = '#ebdbb2'
normalblack = '#282828'
normalred  = '#cc241d'
normalgreen = '#98971a'
normalyellow = '#d79921'
normalblue = '#458588'
normalmagenta = '#b16286'
normalcyan = '#689d6a'
normalwhite = '#a89984'
lightblack = '#928374'
lightred   = '#fb4934'
lightgreen = '#b8bb26'
lightyellow = '#fabd2f'
lightblue  = '#83a598'
lightmagenta = '#d3869b'
lightcyan  = '#8ec07c'
lightwhite = '#ebdbb2'

[line_break]
disabled = false

[username]
show_always = true
style_user = "bg:normalgreen"
style_root = "bg:#9A348E"
format = '[ $user ]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:normalcyan"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:normalmagenta"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:normalmagenta"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:normalblue"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:normalyellow"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:normalyellow"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:normalyellow"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:normalyellow"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:normalyellow"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:normalyellow"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:normalyellow"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:normalyellow"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:normalyellow"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#normalyellow"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:normalyellow"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:normalyellow"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:normalyellow"
format = '[  $time ]($style)'
	
[character]
success_symbol = '[ ➜](lightgreen)'
error_symbol = '[ ➜](lightred)'

[cmd_duration]
min_time = 500
format = ' [$duration](normalyellow)'
